name: Message
description: Builds a PR comment based on preview deploy and Lighthouse info
inputs:
  url:
    description: Deploy URL
  status:
    description: Deploy status
  sha:
    description: Deploy SHA
  links:
    description: Lighthouse links
  results:
    description: Lighthouse assertion results
runs:
  using: node12
  main: message.js
